@url = http://localhost:3000
@identity_provider = http://localhost:8080

###

GET {{url}}/ping

###
POST {{url}}/campaigns
Authorization: Bearer {{access_token}}

{
    "name": "T",
	"content": "isdoasokdakljnlaQue isdoasokdakljnla",
	"emails": ["emailteste.com.br", "outro@gmail.com", "ddklas@dlsaa.com"]
}

###
GET {{url}}/campaigns
Authorization: Bearer {{access_token}}

###
GET {{url}}/campaign/d2mt2o9b6d8utq4ujrr0
Authorization: Bearer {{access_token}}

###
PATCH {{url}}/campaign/cancel/d290q8pb6d8ol7vn3of0

###
DELETE {{url}}/campaign/d1rvgo1b6d8tt4eabhf0

###
# @name token
POST {{identity_provider}}/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=email-campaign-users&username=edmarfilho&password=123456&grant_type=password

### 
@access_token = {{token.response.body.access_token}}